# Generated by Django 4.2.7 on 2023-11-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decription', models.CharField(max_length=256)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
