# Generated by Django 4.2.7 on 2023-11-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_decription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='decription',
            new_name='description',
        ),
    ]
